{{- if .Values.configMap.data -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}
data:
  {{- range $name, $value := .Values.configMap.data }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end -}}